use serde::{Deserialize, Serialize};

// ── State snapshot ──

/// Full runtime state snapshot returned by `get_state`.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct InspectState {
    /// Seconds since monitor started
    pub uptime_secs: u64,
    /// JYC version
    pub version: String,
    /// Configured channels
    pub channels: Vec<ChannelInfo>,
    /// Active topics across all channels
    pub topics: Vec<TopicInfo>,
    /// Aggregate statistics
    pub stats: GlobalStats,
    /// Available commands (name + description), populated from server-side CommandRegistry
    #[serde(default)]
    pub commands: Vec<CommandInfo>,
    /// Available models (name only), populated from agent config providers
    #[serde(default)]
    pub models: Vec<ModelInfo>,
}

/// Slim overview payload returned by `get_state_overview`.
///
/// Same shape as `InspectState` but with `TopicSummary` instead of `TopicInfo`,
/// dropping `activity`, `recent_messages`, and `thinking_text` to keep the
/// per-poll payload small.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct InspectOverview {
    /// Seconds since monitor started
    pub uptime_secs: u64,
    /// JYC version
    pub version: String,
    /// Configured channels
    pub channels: Vec<ChannelInfo>,
    /// Active topics across all channels (lazy summary — no activity/messages)
    pub topics: Vec<TopicSummary>,
    /// Aggregate statistics
    pub stats: GlobalStats,
    /// Available commands (name + description), populated from server-side CommandRegistry
    #[serde(default)]
    pub commands: Vec<CommandInfo>,
    /// Available models (name only), populated from agent config providers
    #[serde(default)]
    pub models: Vec<ModelInfo>,
}

/// Information about an active topic — slim form for the overview page.
///
/// Excludes `activity`, `recent_messages`, and `thinking_text` so the
/// per-poll payload stays small. Use `get_topic_activity` / `get_topic_chat`
/// to fetch these on demand.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicSummary {
    /// Topic name (e.g., "issue-42", "pr-43", "support-ticket")
    pub name: String,
    /// Channel this topic belongs to
    pub channel: String,
    /// Pattern that created this topic (from `.jyc/pattern`)
    pub pattern: Option<String>,
    /// Current processing status
    pub status: TopicStatus,
    /// AI model in use (from model-override or default)
    pub model: Option<String>,
    /// Current mode (plan/build)
    pub mode: Option<String>,
    /// Current input tokens used in this session (= context size, the input
    /// tokens reported by the most recent LLM call). None when the session
    /// has no recorded context yet.
    pub context_input_tokens: Option<u64>,
    /// Max input tokens for this session
    pub max_tokens: Option<u64>,
    /// Running total of output tokens generated by LLM responses in this
    /// session. None when the session has no recorded output yet (fresh
    /// session, file missing, or value zero).
    #[serde(default)]
    pub output_tokens: Option<u64>,
    /// Accumulated input tokens across all LLM calls in this session.
    /// Sums each call's `input_tokens` (= full context size) via `+=`,
    /// so it represents the lifetime total tokens sent to the API for
    /// this session. None when the session has no recorded value yet.
    #[serde(default)]
    pub total_input_tokens: Option<u64>,
    /// Accumulated prompt-cache-hit tokens across all LLM calls in
    /// this session. Sums each call's `cache_hit_tokens` (= tokens
    /// served from the provider's prompt cache rather than re-billed
    /// as fresh input) via `+=`. None when the session has no
    /// recorded value yet (no calls, or the provider didn't surface
    /// cache hits). Not shown in the dashboard overview list — only
    /// in the chat info pane and the dashboard topic info area.
    #[serde(default)]
    pub total_cache_hit_tokens: Option<u64>,
    /// Accumulated prompt-cache-**creation** (write) tokens across
    /// all LLM calls in this session. Anthropic is the only provider
    /// that reports writes separately from reads; for every other
    /// vendor this is `None`. Shown alongside `total_cache_hit_tokens`
    /// in the chat info pane and dashboard topic info area when the
    /// running total is non-zero — i.e., only for Anthropic.
    /// `serde(default)` so old session files (which never wrote the
    /// field) deserialize as `None`.
    #[serde(default)]
    pub total_cache_creation_tokens: Option<u64>,
    /// Last activity timestamp (RFC 3339), if known
    #[serde(default)]
    pub last_active_at: Option<String>,
    /// Skills loaded for this topic
    #[serde(default)]
    pub skills: Vec<String>,
    /// Filesystem path for this topic (may differ from workspace/name when
    /// a pattern's `topic_path` override is active).
    #[serde(default)]
    pub topic_path: Option<std::path::PathBuf>,
    /// Resolved git branch for the topic's working directory, when it is
    /// a git repo. `None` when the path isn't a git repo, or the server
    /// couldn't read `.git/HEAD` (perms, etc.). When the agent clones into
    /// `repo/`, `.git/HEAD` is read under `<topic_path>/repo/`.
    /// `"(detached)"` is returned when HEAD is a raw SHA (no symbolic ref).
    /// `#[serde(default)]` so old payloads (pre-this-field) still load.
    #[serde(default)]
    pub branch: Option<String>,
    /// Files changed relative to `main`. Each path appears at most once,
    /// even when it is both committed on the branch and dirty in the
    /// working tree — when both, `uncommitted` is `true` (the more-noisy
    /// state wins, matches the yellow-render rule in the chat info pane).
    /// Resolved server-side via `git diff --name-only main...HEAD` and
    /// `git diff --name-only HEAD`, then unioned. `None` when the
    /// topic's working directory is not a git repo, or when the `git`
    /// invocations fail (no `main` ref, missing binary). `Some(vec![])`
    /// when both lists come back empty.
    /// `#[serde(default)]` so old payloads (pre-this-field) deserialize
    /// as `None` and the section is simply omitted in the renderer.
    #[serde(default)]
    pub changed_files: Option<Vec<ChangedFileEntry>>,
    /// Accumulated cost (session + today). `None` when the active model
    /// has no configured `pricing`, so the row is omitted entirely
    /// rather than showing a misleading zero.
    #[serde(default)]
    pub cost: Option<TopicCost>,
}

/// Per-file change kind relative to `main`, derived from the status
/// letter in `git diff --name-status main...HEAD`. `Modified` is the
/// default so old payloads (pre-this-field) and absent-on-wire copies
/// fall through as the most common case. The chat info pane renders a
/// one-column prefix glyph per row: `+` for Added, `-` for Deleted,
/// two spaces for Modified. Untracked, renamed, copied, and
/// type-change statuses from `git diff --name-status` are normalized
/// to `Modified` server-side (YAGNI on full status coverage).
#[derive(Debug, Clone, Copy, Default, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum ChangeKind {
    #[default]
    Modified,
    Added,
    Deleted,
}

/// A file in `TopicSummary.changed_files` / `TopicInfo.changed_files`.
///
/// `uncommitted == true` iff the working tree has changes vs HEAD
/// (`git diff --name-only HEAD`); the chat info pane renders such
/// paths in yellow. `change` carries the branch-side status
/// (Added / Modified / Deleted) and is `#[serde(default)]` so old
/// payloads without the field deserialize as `Modified`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ChangedFileEntry {
    pub path: String,
    #[serde(default)]
    pub uncommitted: bool,
    #[serde(default)]
    pub change: ChangeKind,
}

/// Accumulated cost for a topic, in `currency`.
///
/// `session` is scoped to the current agent session and zeroes on
/// reset (read from `agent-session.json`); `today` is the durable
/// per-day total from the billing ledger, which no reset touches.
/// The two are expected to differ after a reset — that is the point
/// of keeping both.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct TopicCost {
    /// Cost of the current session so far.
    pub session: f64,
    /// Cost accumulated today (UTC day), across sessions.
    pub today: f64,
    /// Currency label, e.g. `"USD"`. `"mixed"` when today's entries
    /// span more than one currency, where the summed amount is not a
    /// meaningful single figure.
    pub currency: String,
}

/// Format a cost amount for display.
///
/// Renders `$` for USD and `¥` for CNY (the two currencies the feature
/// was specified against); any other label is shown as a suffix, so an
/// unrecognised currency still reads correctly rather than being
/// mislabelled with the wrong symbol.
///
/// Four decimals: a single cheap call can cost well under a cent, and
/// rounding to 2 places would display it as `0.00`.
pub fn format_amount(amount: f64, currency: &str) -> String {
    match currency {
        "USD" => format!("${amount:.4}"),
        "CNY" => format!("¥{amount:.4}"),
        other => format!("{amount:.4} {other}"),
    }
}

/// Information about a configured channel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelInfo {
    /// Channel name from config (e.g., "emf", "work")
    pub name: String,
    /// Channel type: "email", "feishu", "github"
    pub channel_type: String,
    /// Number of active workers holding semaphore permits in this channel.
    #[serde(default)]
    pub active_workers: usize,
    /// Max concurrent workers allowed for this channel.
    #[serde(default)]
    pub max_concurrent: usize,
}

/// Information about an active topic.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TopicInfo {
    /// Topic name (e.g., "issue-42", "pr-43", "support-ticket")
    pub name: String,
    /// Channel this topic belongs to
    pub channel: String,
    /// Pattern that created this topic (from `.jyc/pattern`)
    pub pattern: Option<String>,
    /// Current processing status
    pub status: TopicStatus,
    /// AI model in use (from model-override or default)
    pub model: Option<String>,
    /// Current mode (plan/build)
    pub mode: Option<String>,
    /// Current input tokens used in this session (= context size).
    pub context_input_tokens: Option<u64>,
    /// Max input tokens for this session
    pub max_tokens: Option<u64>,
    /// Running total of output tokens generated by LLM responses in this
    /// session. Mirrors the same field on `TopicSummary` so the
    /// activity/chat pane can show it without a separate fetch.
    #[serde(default)]
    pub output_tokens: Option<u64>,
    /// Accumulated input tokens across all LLM calls in this session.
    /// See `TopicSummary::total_input_tokens` for the full description.
    #[serde(default)]
    pub total_input_tokens: Option<u64>,
    /// Accumulated prompt-cache-hit tokens across all LLM calls in
    /// this session. See `TopicSummary::total_cache_hit_tokens` for
    /// the full description.
    #[serde(default)]
    pub total_cache_hit_tokens: Option<u64>,
    /// Accumulated prompt-cache-**creation** (write) tokens across
    /// all LLM calls in this session. See
    /// `TopicSummary::total_cache_creation_tokens` for the full
    /// description.
    #[serde(default)]
    pub total_cache_creation_tokens: Option<u64>,
    /// Accumulated reasoning (thinking) tokens across all LLM calls in
    /// this session — the hidden chain-of-thought share of the output,
    /// already included in `output_tokens`. Informational only; `None`
    /// when zero or reported by no provider.
    #[serde(default)]
    pub total_reasoning_tokens: Option<u64>,
    /// Recent activity events (newest first, max ~20)
    #[serde(default)]
    pub activity: Vec<ActivityEntry>,
    /// Last activity timestamp (RFC 3339), if known
    #[serde(default)]
    pub last_active_at: Option<String>,
    /// Skills loaded for this topic
    #[serde(default)]
    pub skills: Vec<String>,
    /// Recent chat messages (incoming + replies) for live dashboard display
    #[serde(default)]
    pub recent_messages: Vec<ChatMessageEntry>,
    /// Latest AI thinking/reasoning text for live dashboard display.
    /// Set while the topic is processing and thinking is enabled; cleared on completion.
    #[serde(default)]
    pub thinking_text: Option<String>,
    /// Filesystem path for this topic (may differ from workspace/name when
    /// a pattern's `topic_path` override is active).
    #[serde(default)]
    pub topic_path: Option<std::path::PathBuf>,
    /// Resolved git branch for the topic's working directory. See
    /// `TopicSummary::branch` for the full semantics.
    #[serde(default)]
    pub branch: Option<String>,
    /// Files changed relative to `main`. See
    /// `TopicSummary::changed_files` for the full semantics; this field
    /// uses the same `Vec<ChangedFileEntry>` shape (path + uncommitted flag).
    #[serde(default)]
    pub changed_files: Option<Vec<ChangedFileEntry>>,
    /// Accumulated cost (session + today). `None` when the active model
    /// has no configured `pricing`, so the row is omitted entirely
    /// rather than showing a misleading zero.
    #[serde(default)]
    pub cost: Option<TopicCost>,
}

/// Severity level for an activity entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum Severity {
    #[default]
    Info,
    Warning,
    Error,
}

/// A single activity event from the topic's SSE stream.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityEntry {
    /// Human-readable description
    pub text: String,
    /// RFC 3339 timestamp for ordering and cross-day sorting
    #[serde(default)]
    pub timestamp: Option<String>,
    /// Severity level (defaults to Info for backward compat)
    #[serde(default)]
    pub severity: Severity,
    /// Monotonic per-topic sequence number assigned by the inspect server's
    /// `ActivityTracker` on push. Used by WS clients to drop duplicate events
    /// after a reconnect / Lagged recovery. Defaults to 0 for entries from
    /// `.jyc/activity.jsonl` that predate the seq field.
    #[serde(default)]
    pub id: u64,
    /// Internal events are useful for debug logs but should NOT be shown in
    /// user-facing surfaces (overview activity pane, chat activity pane,
    /// chat progress, REST `get_topic_activity` response). Currently set
    /// for `ProcessingProgress` heartbeats (e.g. "tool execution (Xs, Y
    /// chars)"). Defaults to `false` for backward compat with old log
    /// entries that predate this field.
    #[serde(default)]
    pub is_internal: bool,
}

/// A chat message entry for live display in the dashboard.
///
/// Captured from `TopicEvent::IncomingMessage` and `TopicEvent::ReplySent`
/// by the ActivityTracker and forwarded via `TopicInfo.recent_messages`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatMessageEntry {
    /// Sender label: "user", "ai", or a display name
    pub sender: String,
    /// Message or reply text
    pub text: String,
    /// RFC 3339 timestamp
    #[serde(default)]
    pub timestamp: Option<String>,
    /// Monotonic per-topic sequence number (see `ActivityEntry::id`).
    #[serde(default)]
    pub id: u64,
}

/// Topic processing status.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
#[derive(Default)]
pub enum TopicStatus {
    /// Waiting for semaphore permit
    Queued,
    /// AI processing active
    Processing,
    /// Worker running, waiting for messages
    #[default]
    Idle,
    /// Question tool waiting for user reply
    WaitingForAnswer,
    /// Topic encountered an error
    Error,
}

impl std::fmt::Display for TopicStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Queued => write!(f, "Queued"),
            Self::Processing => write!(f, "Processing"),
            Self::Idle => write!(f, "Idle"),
            Self::WaitingForAnswer => write!(f, "Waiting"),
            Self::Error => write!(f, "Error"),
        }
    }
}

/// Aggregate statistics.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct GlobalStats {
    /// Number of active workers (holding semaphore permits)
    pub active_workers: usize,
    /// Total number of open topics
    pub total_topics: usize,
    /// Max concurrent workers allowed
    pub max_concurrent: usize,
    /// Number of available worker slots (max_concurrent - active_workers)
    pub available_workers: usize,
    /// Total messages received since startup
    pub messages_received: u64,
    /// Total messages processed since startup
    pub messages_processed: u64,
    /// Total errors since startup
    pub errors: u64,
}

/// Information about an available command (name + description).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommandInfo {
    /// Command name including slash (e.g., "/model")
    pub name: String,
    /// Short description (e.g., "Switch AI model for this topic")
    pub description: String,
}

/// Information about an available model (name only, for model picker UI).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ModelInfo {
    /// Full model identifier (e.g., "deepseek/deepseek-chat", "claude-sonnet-4-6")
    pub name: String,
}

// ── Protocol constants ──

/// Extract a short human-readable summary of a tool call from
/// the `ToolStarted` event's JSON input: `service/tools.rs` for file tools,
/// the command for `bash`, the pattern for `grep`/`glob`, the URL for
/// `webfetch`. Shared by every surface that displays a tool call (Feishu
/// status card, TUI chat progress tail).
///
/// File paths are reduced to their basename; newlines/excess whitespace are
/// collapsed so a multi-line command stays on one display line; the result
/// is truncated to 160 chars with an ellipsis. Tools without a meaningful
/// argument (or with sensitive args like the reply text) return `None` —
/// callers decide whether to fall back to the raw input or show nothing.
pub fn tool_activity_summary(tool_name: &str, input: Option<&str>) -> Option<String> {
    let get = |key: &str| -> Option<String> {
        serde_json::from_str::<serde_json::Value>(input?)
            .ok()?
            .get(key)?
            .as_str()
            .map(str::to_string)
    };
    let raw = match tool_name {
        // File tools: basename keeps the display short (read_image names its
        // argument "path", the others "file_path").
        "read" | "edit" | "write" | "read_image" => {
            let p = get("file_path").or_else(|| get("path"))?;
            p.rsplit('/').next().unwrap_or(&p).to_string()
        }
        "grep" | "glob" => get("pattern")?,
        "bash" => get("command")?,
        "webfetch" => get("url")?,
        _ => return None,
    };
    let flat = raw.split_whitespace().collect::<Vec<_>>().join(" ");
    const MAX: usize = 160;
    if flat.chars().count() > MAX {
        Some(flat.chars().take(MAX - 1).collect::<String>() + "…")
    } else {
        Some(flat)
    }
}

/// Default TCP port for the inspect server.
pub const DEFAULT_INSPECT_PORT: u16 = 9876;

/// Default bind address for the inspect server.
pub const DEFAULT_INSPECT_BIND: &str = "127.0.0.1:9876";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_inspect_state_serialize_roundtrip() {
        let state = InspectState {
            uptime_secs: 3600,
            version: "0.1.10".to_string(),
            channels: vec![ChannelInfo {
                name: "emf".to_string(),
                channel_type: "github".to_string(),
                active_workers: 2,
                max_concurrent: 3,
            }],
            topics: vec![TopicInfo {
                name: "issue-42".to_string(),
                channel: "emf".to_string(),
                pattern: Some("planner".to_string()),
                status: TopicStatus::Processing,
                model: Some("anthropic/claude-opus-4-6".to_string()),
                mode: Some("build".to_string()),
                context_input_tokens: Some(45000),
                max_tokens: Some(120000),
                output_tokens: Some(12345),
                total_input_tokens: Some(45000),
                total_cache_hit_tokens: None,
                total_cache_creation_tokens: None,
                total_reasoning_tokens: None,
                activity: vec![],
                last_active_at: None,
                skills: vec!["coding-principles".to_string(), "dev-workflow".to_string()],
                recent_messages: vec![],
                thinking_text: None,
                topic_path: None,
                branch: None,
                changed_files: None,
                cost: None,
            }],
            stats: GlobalStats {
                active_workers: 2,
                total_topics: 3,
                max_concurrent: 3,
                available_workers: 1,
                messages_received: 156,
                messages_processed: 150,
                errors: 2,
            },
            commands: vec![],
            models: vec![],
        };

        let json = serde_json::to_string(&state).unwrap();
        let parsed: InspectState = serde_json::from_str(&json).unwrap();

        assert_eq!(parsed.uptime_secs, 3600);
        assert_eq!(parsed.channels.len(), 1);
        assert_eq!(parsed.channels[0].name, "emf");
        assert_eq!(parsed.channels[0].active_workers, 2);
        assert_eq!(parsed.channels[0].max_concurrent, 3);
        assert_eq!(parsed.topics.len(), 1);
        assert_eq!(parsed.topics[0].status, TopicStatus::Processing);
        assert_eq!(parsed.stats.active_workers, 2);
    }

    #[test]
    fn test_topic_status_display() {
        assert_eq!(format!("{}", TopicStatus::Queued), "Queued");
        assert_eq!(format!("{}", TopicStatus::Processing), "Processing");
        assert_eq!(format!("{}", TopicStatus::Idle), "Idle");
        assert_eq!(format!("{}", TopicStatus::WaitingForAnswer), "Waiting");
        assert_eq!(format!("{}", TopicStatus::Error), "Error");
    }

    #[test]
    fn test_inspect_state_default() {
        let state = InspectState::default();
        assert_eq!(state.uptime_secs, 0);
        assert!(state.channels.is_empty());
        assert!(state.topics.is_empty());
        assert_eq!(state.stats.active_workers, 0);
    }

    #[test]
    fn test_topic_status_serde() {
        // TopicStatus serializes to snake_case
        let json = serde_json::to_string(&TopicStatus::WaitingForAnswer).unwrap();
        assert_eq!(json, r#""waiting_for_answer""#);

        let parsed: TopicStatus = serde_json::from_str(r#""processing""#).unwrap();
        assert_eq!(parsed, TopicStatus::Processing);

        let json = serde_json::to_string(&TopicStatus::Error).unwrap();
        assert_eq!(json, r#""error""#);

        let parsed: TopicStatus = serde_json::from_str(r#""error""#).unwrap();
        assert_eq!(parsed, TopicStatus::Error);
    }

    #[test]
    fn test_severity_serde_roundtrip() {
        let json = serde_json::to_string(&Severity::Info).unwrap();
        assert_eq!(json, r#""info""#);
        let parsed: Severity = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, Severity::Info);

        let json = serde_json::to_string(&Severity::Warning).unwrap();
        assert_eq!(json, r#""warning""#);
        let parsed: Severity = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, Severity::Warning);

        let json = serde_json::to_string(&Severity::Error).unwrap();
        assert_eq!(json, r#""error""#);
        let parsed: Severity = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, Severity::Error);
    }

    #[test]
    fn test_severity_default_is_info() {
        assert_eq!(Severity::default(), Severity::Info);
    }

    #[test]
    fn test_activity_entry_backward_compat_old_jsonl() {
        // Old JSONL entries have `time` field but no `severity` — should deserialize fine
        let old_json =
            r#"{"time":"12:34:56","text":"Processing started","timestamp":"2025-01-15T12:34:56Z"}"#;
        let entry: ActivityEntry = serde_json::from_str(old_json).unwrap();
        assert_eq!(entry.text, "Processing started");
        assert_eq!(entry.severity, Severity::Info);
        assert_eq!(entry.timestamp.as_deref(), Some("2025-01-15T12:34:56Z"));
    }

    #[test]
    fn test_activity_entry_with_severity() {
        let entry = ActivityEntry {
            text: "Failed (5s)".to_string(),
            timestamp: Some("2025-01-15T12:34:56Z".to_string()),
            severity: Severity::Error,
            id: 0,
            is_internal: false,
        };
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains(r#""severity":"error""#));
        let parsed: ActivityEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.severity, Severity::Error);
    }

    #[test]
    fn test_activity_entry_id_backward_compat() {
        // Old JSONL entries have no `id` field — should default to 0
        let old_json =
            r#"{"text":"old entry","timestamp":"2025-01-15T12:00:00Z","severity":"info"}"#;
        let entry: ActivityEntry = serde_json::from_str(old_json).unwrap();
        assert_eq!(entry.id, 0);
        assert_eq!(entry.text, "old entry");
    }

    #[test]
    fn test_activity_entry_id_roundtrip() {
        let entry = ActivityEntry {
            text: "new entry".to_string(),
            timestamp: Some("2025-01-15T12:00:00Z".to_string()),
            severity: Severity::Info,
            id: 42,
            is_internal: false,
        };
        let json = serde_json::to_string(&entry).unwrap();
        assert!(json.contains(r#""id":42"#));
        let parsed: ActivityEntry = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.id, 42);
    }

    #[test]
    fn test_chat_message_entry_id_backward_compat() {
        let old_json = r#"{"sender":"user","text":"hi","timestamp":"2025-01-15T12:00:00Z"}"#;
        let entry: ChatMessageEntry = serde_json::from_str(old_json).unwrap();
        assert_eq!(entry.id, 0);
        assert_eq!(entry.sender, "user");
    }

    #[test]
    fn test_channel_info_backward_compat() {
        let old_json = r#"{"name":"emf","channel_type":"github"}"#;
        let ch: ChannelInfo = serde_json::from_str(old_json).unwrap();
        assert_eq!(ch.name, "emf");
        assert_eq!(ch.active_workers, 0);
        assert_eq!(ch.max_concurrent, 0);
    }

    #[test]
    fn test_topic_summary_roundtrip() {
        let summary = TopicSummary {
            name: "issue-42".to_string(),
            channel: "emf".to_string(),
            pattern: Some("planner".to_string()),
            status: TopicStatus::Processing,
            model: Some("claude-opus".to_string()),
            mode: Some("build".to_string()),
            context_input_tokens: Some(10000),
            max_tokens: Some(120000),
            output_tokens: Some(2000),
            total_input_tokens: Some(10000),
            total_cache_hit_tokens: Some(8000),
            total_cache_creation_tokens: None,
            last_active_at: Some("2026-01-01T00:00:00Z".to_string()),
            skills: vec!["dev-workflow".to_string()],
            topic_path: None,
            branch: None,
            changed_files: None,
            cost: None,
        };
        let json = serde_json::to_string(&summary).unwrap();
        let parsed: TopicSummary = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.name, "issue-42");
        assert_eq!(parsed.status, TopicStatus::Processing);
        // TopicSummary must not serialize activity/messages/thinking fields
        assert!(!json.contains("activity"));
        assert!(!json.contains("recent_messages"));
        assert!(!json.contains("thinking_text"));
    }

    #[test]
    fn test_inspect_overview_roundtrip() {
        let overview = InspectOverview {
            uptime_secs: 100,
            version: "0.1.0".to_string(),
            channels: vec![],
            topics: vec![],
            stats: GlobalStats::default(),
            commands: vec![],
            models: vec![],
        };
        let json = serde_json::to_string(&overview).unwrap();
        // InspectOverview is a struct (not a tagged-enum variant), so no `type` tag
        assert!(json.contains(r#""uptime_secs":100"#));
        assert!(json.contains(r#""version":"0.1.0""#));
        let parsed: InspectOverview = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed.uptime_secs, 100);
    }

    #[test]
    fn tool_activity_summary_extracts_basename_for_file_tools() {
        let input =
            r#"{"file_path": "/home/jiny/projects/jyc/crates/jyc-agent/src/service/tools.rs"}"#;
        assert_eq!(
            tool_activity_summary("edit", Some(input)).as_deref(),
            Some("tools.rs")
        );
        assert_eq!(
            tool_activity_summary("read", Some(input)).as_deref(),
            Some("tools.rs")
        );
        assert_eq!(
            tool_activity_summary("write", Some(input)).as_deref(),
            Some("tools.rs")
        );
        // read_image names its argument "path", not "file_path".
        assert_eq!(
            tool_activity_summary("read_image", Some(r#"{"path": "/tmp/x/photo.png"}"#)).as_deref(),
            Some("photo.png")
        );
    }

    #[test]
    fn tool_activity_summary_extracts_command_pattern_url() {
        assert_eq!(
            tool_activity_summary("bash", Some(r#"{"command": "ls -la"}"#)).as_deref(),
            Some("ls -la")
        );
        assert_eq!(
            tool_activity_summary("grep", Some(r#"{"pattern": "fn main"}"#)).as_deref(),
            Some("fn main")
        );
        assert_eq!(
            tool_activity_summary("webfetch", Some(r#"{"url": "https://example.com"}"#)).as_deref(),
            Some("https://example.com")
        );
        // Unknown tools and tools with sensitive args produce no summary.
        assert_eq!(tool_activity_summary("jyc_reply_message", Some("{}")), None);
        assert_eq!(tool_activity_summary("bash", None), None);
        assert_eq!(tool_activity_summary("bash", Some("not json")), None);
    }

    #[test]
    fn tool_activity_summary_truncates_and_flattens() {
        let long = "a".repeat(200);
        let input = format!(r#"{{"command": "{long}"}}"#);
        let got = tool_activity_summary("bash", Some(&input)).unwrap();
        assert_eq!(got.chars().count(), 160);
        assert!(got.ends_with('…'));

        // Newlines collapse to spaces so a multi-line command stays on one
        // display line.
        let multi = r#"{"command": "ls\n   -la"}"#;
        assert_eq!(
            tool_activity_summary("bash", Some(multi)).as_deref(),
            Some("ls -la")
        );
    }
}
